### ISSUE TITLE
not blocking other country

### ISSUE THREAD

**Issue by githubsonali** [ilich/node-ipgeoblock#3]
why node-ipgeoblock is not blocking other countries? when i'm adding "IN" for blocking India using blockedCountries: [ "FR", "GB", "DE" ,"IN"] then why it is not working?

**Comment by ilich** [comment]
Most probably  your IP address in not in MaxMind database. When you use blockedCountries property, all countries are allowed except the one specified in the list. I'd suggest to debug ```function isBlocked(ip, req, res)``` and see what's going on there for a particular IP address.
